### PR TITLE
Remove `transitive` modifier from optional dependencies

### LINKED ISSUE #2929: Compiling with `2.24.0` fails: `module not found: org.jspecify`
## Description

I have a modular (Jigsaw) project that uses log4j2. Compilation fails after updating to 2.24.0 from 2.23.1 with the error "".

## Configuration

**Version:** 2.24.0

**Operating system:** macOS 14.6.1

**JDK:** 

openjdk 21.0.4 2024-07-16 LTS
OpenJDK Runtime Environment (build 21.0.4+9-LTS)
OpenJDK 64-Bit Server VM (build 21.0.4+9-LTS, mixed mode, sharing)

## Logs

Running my gradle build, I get this:
```
23:21:38: Executing 'build'...

> Task :utility-logging:processResources NO-SOURCE
> Task :utility-fx-web:generateCatalogAsToml FROM-CACHE
> Task :generateCatalogAsToml FROM-CACHE
> Task :utility-db:generateCatalogAsToml FROM-CACHE
> Task :utility-logging:generateCatalogAsToml FROM-CACHE
> Task :utility:generateCatalogAsToml FROM-CACHE
> Task :utility-fx-icons-ikonli:generateCatalogAsToml FROM-CACHE
> Task :utility-fx-db:generateCatalogAsToml FROM-CACHE
> Task :utility-fx:generateCatalogAsToml FROM-CACHE
> Task :utility-fx-web:processResources NO-SOURCE
> Task :utility-fx-controls:generateCatalogAsToml FROM-CACHE
> Task :compileJava NO-SOURCE
> Task :utility-fx-db:processResources NO-SOURCE
> Task :utility-db:processResources
> Task :utility-fx:processResources
> Task :utility-fx-controls:processResources
> Task :utility-fx-icons-ikonli:processResources

> Task :utility-fx-icons:compileJava FAILED

> Task :utility-logging:sourcesJar
> Task :utility-fx-icons-ikonli:sourcesJar
> Task :utility-fx-db:sourcesJar
> Task :utility-fx-web:sourcesJar
> Task :utility-fx:sourcesJar
> Task :utility-fx-controls:sourcesJar
error: module not found: org.jspecify
1 error
> Task :utility-db:sourcesJar
> Task :cabe

> Task :utility:compileJava FAILED
23 actionable tasks: 14 executed, 9 from cache
error: module not found: org.jspecify
1 error

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':utility-fx-icons:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --info option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':utility:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --info option to get more log output.
> Run with --scan to get full insights.
==============================================================================

BUILD FAILED in 448ms
23:21:39: Execution finished 'build'.
```

## Reproduction

Sorry, still have not had the time to create a minimal project. I think any project using modules working with 2.23.1 should expose the error  - I still need to investigate. But changing the log4j2 version is the only change I did before running into this error and changing back to 2.23.1 fixed it. Compile with version 2.23.1, then try again using 2.24.0.

My project does (obviously) not use jspecify, adding it as a dependency will probably fix it.

I see this in the log4j-core module-info.class and think jspecify should be a transitive dependency and the static might have to be removed:
```
        requires static transitive org.jspecify;
```

### PR DESCRIPTION
**Pull request by ppkarwasz**
This PR:

- Add a Groovy script that checks the generated `module-info.class` files for `static transitive` dependencies.
- Modifies the BND configuration not to mark `org.jspecify` as `transitive`.

We remove the `transitive` modifier from all optional dependencies.

Closes #2929.

**Note**: Once these changes are accepted, I'll move the Groovy script to `logging-parent` and implement apache/logging-parent#196 too.

### CODE REVIEW

File: log4j-parent/pom.xml [hunk 1]
```diff
@@ -995,6 +996,55 @@
         </executions>
       </plugin>
 
+      <plugin>
+        <groupId>org.codehaus.gmavenplus</groupId>
+        <artifactId>gmavenplus-plugin</artifactId>
+        <version>${gmavenplus-plugin.version}</version>
+        <configuration>
```
Comment (vy) [inline log4j-parent/pom.xml:1003]: Could you move `configuration` inside the `execution`, please?

**Review by vy — COMMENTED** [review]
Question: Shouldn't we instead

* enforce a whitelist of `static` dependencies (so every optional will need to be a conscious decision, not a mistake) and
* ban `transitive static`?

File: log4j-parent/pom.xml (hunk 1 above)
Comment (ppkarwasz) [reply log4j-parent/pom.xml]: Fixed in https://github.com/apache/logging-log4j2/pull/2930/commits/c3db320ab279ece57e97a36a8b7cae52cdf2f338

File: log4j-parent/pom.xml [hunk 2]
```diff
@@ -995,6 +996,68 @@
...
+                  if (result != 0) {
+                      throw new RuntimeException('Failed to decompile the module descriptor in ' + jarFile + ':\n' + err)
+                  }
+                  log.debug('Module descriptor: ' + out)
+                  for (String line : out.toString().split('\r?\n', -1)) {
+                      if (line.contains('static') && line.contains('transitive')) {
+                          throw new RuntimeException("The 'static' and 'transitive' modifiers should not be use together: " + line)
+                      }
+                  }
+                  log.info('Successfully verified module descriptor in `' + jarFile + '`.')
```
Comment (vy) [inline log4j-parent/pom.xml:1053]: Improve consistency of double-quote usage for string literals:
```suggestion
                      log.info("Skipping module descriptor check, since the project type is not `jar`.")
                      return
                  }
                  String jarFile = project.build.directory + "/" + project.build.finalName + ".jar";
                  if (!new File(jarFile).exists()) {
                      log.info("Skipping module descriptor check, since `" + jarFile + "` is missing.")
                      return
                  }
                  StringWriter out = new StringWriter()
                  StringWriter err = new StringWriter()
                  ToolProvider jar = ToolProvider.findFirst("jar").orElseThrow()
                  int result = jar.run(new PrintWriter(out), new PrintWriter(err), "-d", "-f", jarFile)
                  if (result != 0) {
                      throw new RuntimeException("Failed to decompile the module descriptor in `" + jarFile + "`:\n" + err)
                  }
                  log.debug("Module descriptor: " + out)
                  for (String line : out.toString().split("\r?\n", -1)) {
                      if (line.contains("static") && line.contains("transitive")) {
                          throw new RuntimeException("The `static` and `transitive` modifiers should not be use together: " + line)
                      }
                  }
                  log.info("Successfully verified module descriptor in `" + jarFile + "`.")
```
